# -*- coding: utf-8 -*-
"""imputers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LtTZ8snvXmrPU1dp6eqeI0J3JIFztBh1
"""

"""
ML-based Imputation
-------------------------------------------------------
Statistical (mean/median/mode) + ML-based (KNN, Iterative/Regression) imputation।
"""

import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import KNNImputer, IterativeImputer, SimpleImputer
from sklearn.linear_model import BayesianRidge


def statistical_impute(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    numeric_cols = out.select_dtypes(include="number").columns
    cat_cols = out.select_dtypes(exclude="number").columns

    if len(numeric_cols) > 0:
        num_imputer = SimpleImputer(strategy="median")
        out[numeric_cols] = num_imputer.fit_transform(out[numeric_cols])
    if len(cat_cols) > 0:
        cat_imputer = SimpleImputer(strategy="most_frequent")
        out[cat_cols] = cat_imputer.fit_transform(out[cat_cols])
    return out


def knn_impute(df: pd.DataFrame, n_neighbors: int = 3) -> pd.DataFrame:
    """for only neumeric column KNN-based imputation।"""
    out = df.copy()
    numeric_cols = out.select_dtypes(include="number").columns
    if len(numeric_cols) == 0:
        return out
    imputer = KNNImputer(n_neighbors=n_neighbors)
    out[numeric_cols] = imputer.fit_transform(out[numeric_cols])
    return out


def iterative_impute(df: pd.DataFrame, max_iter: int = 10) -> pd.DataFrame:
    """Regression-based (Bayesian Ridge) iterative imputer — numeric for neumeric column।"""
    out = df.copy()
    numeric_cols = out.select_dtypes(include="number").columns
    if len(numeric_cols) == 0:
        return out
    imputer = IterativeImputer(estimator=BayesianRidge(), max_iter=max_iter, random_state=42)
    out[numeric_cols] = imputer.fit_transform(out[numeric_cols])
    return out


IMPUTATION_STRATEGIES = {
    "statistical": statistical_impute,
    "knn": knn_impute,
    "iterative": iterative_impute,
}