# -*- coding: utf-8 -*-
"""metadata_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmUrUNjr-JHEVOI0OOkZo2z5CiWDjQHh
"""

import re
import pandas as pd

BD_PHONE_RE = re.compile(r"^(\+?880|0)1[3-9]\d{8}$")
BD_NID_RE = re.compile(r"^\d{10}$|^\d{13}$|^\d{17}$")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

SEMANTIC_RULES = {
    "phone": lambda s: s.astype(str).str.strip().str.match(BD_PHONE_RE).mean(),
    "nid": lambda s: s.astype(str).str.strip().str.match(BD_NID_RE).mean(),
    "email": lambda s: s.astype(str).str.strip().str.match(EMAIL_RE).mean(),
    "date": lambda s: s.astype(str).str.strip().str.match(DATE_RE).mean(),
}


def infer_column_types(df: pd.DataFrame) -> dict:
    result = {}
    for col in df.columns:
        dtype = str(df[col].dtype)
        result[col] = {"pandas_dtype": dtype}
    return result


def detect_semantic_meaning(df: pd.DataFrame, threshold: float = 0.6) -> dict:
    semantics = {}
    for col in df.select_dtypes(include="object").columns:
        non_null = df[col].dropna()
        if non_null.empty:
            semantics[col] = None
            continue
        best_type, best_score = None, 0.0
        for sem_type, rule in SEMANTIC_RULES.items():
            try:
                score = rule(non_null)
            except Exception:
                score = 0.0
            if score > best_score:
                best_type, best_score = sem_type, score
        semantics[col] = best_type if best_score >= threshold else None
    return semantics


def detect_mixed_type_columns(df: pd.DataFrame) -> list:
    mixed = []
    for col in df.columns:
        types_seen = df[col].dropna().map(lambda v: type(v).__name__).unique()
        if len(types_seen) > 1:
            mixed.append({"column": col, "types_found": list(types_seen)})
    return mixed


def extract_metadata(df: pd.DataFrame) -> dict:
    return {
        "n_rows": len(df),
        "n_columns": len(df.columns),
        "column_types": infer_column_types(df),
        "semantic_meaning": detect_semantic_meaning(df),
        "mixed_type_columns": detect_mixed_type_columns(df),
    }