# -*- coding: utf-8 -*-
"""profiler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LEqhjVvjQoEy2ZN-DyPN6XuF2aQXOkJz
"""

import numpy as np
import pandas as pd


def missing_value_matrix(df: pd.DataFrame) -> dict:
    missing_count = df.isna().sum()
    missing_pct = (missing_count / len(df) * 100).round(2)
    return {
        col: {"missing_count": int(missing_count[col]), "missing_pct": float(missing_pct[col])}
        for col in df.columns
    }


def dtype_consistency_check(df: pd.DataFrame) -> dict:
    report = {}
    for col in df.columns:
        if df[col].dtype == object:
            numeric_like = pd.to_numeric(df[col], errors="coerce").notna()
            inconsistent = int((numeric_like & df[col].notna()).sum())
            report[col] = {"note": f"{inconsistent} string values look numeric"} if inconsistent else {"note": "consistent"}
        else:
            report[col] = {"note": "consistent"}
    return report


def cardinality_analysis(df: pd.DataFrame) -> dict:
    return {
        col: {
            "unique_values": int(df[col].nunique(dropna=True)),
            "cardinality_ratio": round(df[col].nunique(dropna=True) / max(len(df), 1), 4),
        }
        for col in df.columns
    }


def correlation_matrix(df: pd.DataFrame) -> dict:
    numeric_df = df.select_dtypes(include=[np.number])
    if numeric_df.shape[1] < 2:
        return {}
    corr = numeric_df.corr(numeric_only=True).round(3)
    return corr.fillna(0).to_dict()


def outlier_distribution(df: pd.DataFrame) -> dict:
    numeric_df = df.select_dtypes(include=[np.number])
    result = {}
    for col in numeric_df.columns:
        s = numeric_df[col].dropna()
        if s.empty:
            result[col] = {"outlier_count": 0}
            continue
        q1, q3 = s.quantile(0.25), s.quantile(0.75)
        iqr = q3 - q1
        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        outliers = s[(s < lower) | (s > upper)]
        result[col] = {"outlier_count": int(len(outliers)), "lower_bound": round(float(lower), 2), "upper_bound": round(float(upper), 2)}
    return result


def run_profiling(df: pd.DataFrame) -> dict:
    return {
        "missing_value_matrix": missing_value_matrix(df),
        "dtype_consistency": dtype_consistency_check(df),
        "cardinality": cardinality_analysis(df),
        "correlation_matrix": correlation_matrix(df),
        "outlier_distribution": outlier_distribution(df),
    }





