# -*- coding: utf-8 -*-
"""schema_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DW9YK7w6P5914EWvYJQ5e_9Sm_sMzHre
"""

import numpy as np
import pandas as pd


def infer_schema(df: pd.DataFrame) -> dict:
    schema = {}
    for col in df.columns:
        s = df[col]
        if pd.api.types.is_numeric_dtype(s):
            non_null = s.dropna()
            schema[col] = {
                "expected_type": "numeric",
                "expected_range": [
                    float(non_null.min()) if not non_null.empty else None,
                    float(non_null.max()) if not non_null.empty else None,
                ],
            }
        else:
            lengths = s.dropna().astype(str).map(len)
            schema[col] = {
                "expected_type": "categorical/string",
                "expected_format_length": [int(lengths.min()) if not lengths.empty else None,
                                            int(lengths.max()) if not lengths.empty else None],
            }
    return schema